#!/bin/bash
INIT_DIR='/etc/init'

cp health_check.conf $INIT_DIR
chown root:root $INIT_DIR/health_check.conf
echo "exec `pwd`/start_health_check" >> $INIT_DIR/health_check.conf
stop health_check
start health_check
