#!/usr/bin/env ruby
require 'fileutils'

INIT_DIR = '/etc/init'
start_health_check_script = {
  filename: 'start_health_check'
}

start_health_check_script[:code] = <<-eos
  #!/bin/bash

  set -u
  set -e

  INIT_RBENV='export PATH=$PATH:$HOME/.rbenv/bin; eval "$(rbenv init -)"'

  CMD="$INIT_RBENV; cd '#{Dir.pwd}'; ruby health_check.rb"

  su - #{ENV['USER']} -c "$CMD";
eos

File.open(start_health_check_script[:filename], 'w') { |f| f.write start_health_check_script[:code] }

`chmod +x #{start_health_check_script[:filename]}`

FileUtils.copy "health_check.conf", "health_check.conf.temp"
File.open("health_check.conf.temp", 'a') {|f| f.write "exec #{Dir.pwd}/#{start_health_check_script[:filename]}" }

sudo_cmds = [
  'mkdir -p /var/log/upstart',
  "mv health_check.conf.temp #{INIT_DIR}/health_check.conf",
  "chown root:root #{INIT_DIR}/health_check.conf",
  'stop health_check',
  'start health_check',
]

sudo_cmds.each { |c| system "sudo #{c}" }
